### ISSUE TITLE
Error watch - (react-native-i18n/android/build/intermediates)

### ISSUE THREAD

**Issue by moaxaca** [AlexanderZaytsev/react-native-i18n#54]
System:
OS: Ubuntu 16.0.4
Node: v6.4.0
NPM: v3.10.3

react-native-cli: 2.0.1
react-native: 0.40.0

On start it immediately crashes with this error. 

Package Error:
ERROR  watch /home/user/Concise/react-native-app/node_modules/react-native-i18n/android/build/intermediates/bundles/release/aapt ENOSPC
{"code":"ENOSPC","errno":"ENOSPC","syscall":"watch /home/user/Concise/react-native-app/node_modules/react-native-i18n/android/build/intermediates/bundles/release/aapt","filename":"/home/user/Concise/react-native-app/node_modules/react-native-i18n/android/build/intermediates/bundles/release/aapt"}
Error: watch /home/user/Concise/react-native-app/node_modules/react-native-i18n/android/build/intermediates/bundles/release/aapt ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at NodeWatcher.watchdir (/home/user/Concise/react-native-app/node_modules/sane/src/node_watcher.js:144:20)
    at Walker.<anonymous> (/home/user/Concise/react-native-app/node_modules/sane/src/node_watcher.js:353:12)
    at emitTwo (events.js:106:13)
    at Walker.emit (events.js:191:7)
    at Walker.EventEmitter.emit (/home/user/Concise/react-native-app/node_modules/sc-domain/index.js:12:31)
    at /home/user/Concise/react-native-app/node_modules/walker/lib/walker.js:69:16
    at go$readdir$cb (/home/user/Concise/react-native-app/node_modules/graceful-fs/graceful-fs.js:149:14)

Stack Trace: 
0 info it worked if it ends with ok
1 verbose cli [ '/home/user/.nvm/versions/node/v6.4.0/bin/node',
1 verbose cli   '/home/user/.nvm/versions/node/v6.4.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.10.3
3 info using node@v6.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-native-app@0.0.1~prestart: react-native-app@0.0.1
6 silly lifecycle react-native-app@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle react-native-app@0.0.1~start: react-native-app@0.0.1
8 verbose lifecycle react-native-app@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle react-native-app@0.0.1~start: PATH: /home/user/.nvm/versions/node/v6.4.0/lib/node_modules/npm/bin/node-gyp-bin:/home/user/Concise/react-native-app/node_modules/.bin:/home/user/.nvm/versions/node/v6.4.0/bin:/home/user/.nvm/versions/node/v6.4.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/local/bin:/home/user/Android/Sdk/tools:/home/user/Android/Sdk/platform-tools
10 verbose lifecycle react-native-app@0.0.1~start: CWD: /home/user/Concise/react-native-app
11 silly lifecycle react-native-app@0.0.1~start: Args: [ '-c',
11 silly lifecycle   'node node_modules/react-native/local-cli/cli.js start' ]
12 silly lifecycle react-native-app@0.0.1~start: Returned: code: 11  signal: null
13 info lifecycle react-native-app@0.0.1~start: Failed to exec start script
14 verbose stack Error: react-native-app@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
14 verbose stack Exit status 11
14 verbose stack     at EventEmitter.<anonymous> (/home/user/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/user/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid react-native-app@0.0.1
16 verbose cwd /home/user/Concise/react-native-app
17 error Linux 4.4.0-59-generic
18 error argv "/home/user/.nvm/versions/node/v6.4.0/bin/node" "/home/user/.nvm/versions/node/v6.4.0/bin/npm" "start"
19 error node v6.4.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error react-native-app@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
22 error Exit status 11
23 error Failed at the react-native-app@0.0.1 start script 'node node_modules/react-native/local-cli/cli.js start'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-native-app package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node node_modules/react-native/local-cli/cli.js start
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-native-app
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-native-app
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by moaxaca** [comment]
It was a inotify(7) related error. 

I just had to up the values on:
/proc/sys/fs/inotify/max_user_instances
/proc/sys/fs/inotify/max_user_watches
/proc/sys/fs/inotify/max_queued_events
